[package]
name = "jp"
version = "0.4.0"
authors = ["Brian McCallister <brianm@skife.org>"]
build = "build.rs"
edition = "2021"

[dependencies]
serde_json = "1"
clap = { version = "4", features = ["derive"] }
human-panic = "2"
anyhow = "1"
